"""
Parser for enriched call features exported from MATLAB.

Reads CSV files generated by ExportEnrichedFeatures.m containing 11 features per call.
"""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd


# Feature column names in the CSV (order matters)
FEATURE_COLUMNS = [
    'duration',
    'low_freq',
    'high_freq',
    'principal_freq',
    'bandwidth',
    'freq_stdev',
    'slope',
    'sinuosity',
    'snr',
    'entropy',
    'mean_power',
]

N_FEATURES = len(FEATURE_COLUMNS)


@dataclass
class EnrichedCallData:
    """Container for enriched call features from MATLAB export."""

    duration: np.ndarray          # (n_calls,) - Call length (seconds)
    low_freq: np.ndarray          # (n_calls,) - Minimum frequency (kHz)
    high_freq: np.ndarray         # (n_calls,) - Maximum frequency (kHz)
    principal_freq: np.ndarray    # (n_calls,) - Median frequency (kHz)
    bandwidth: np.ndarray         # (n_calls,) - Frequency range (kHz)
    freq_stdev: np.ndarray        # (n_calls,) - Frequency standard deviation
    slope: np.ndarray             # (n_calls,) - Frequency trajectory slope
    sinuosity: np.ndarray         # (n_calls,) - Contour curvature ratio
    snr: np.ndarray               # (n_calls,) - Signal to noise ratio
    entropy: np.ndarray           # (n_calls,) - Spectrogram entropy
    mean_power: np.ndarray        # (n_calls,) - Average power (dB)

    # Metadata
    filename: str
    n_calls: int

    def get_feature_matrix(self) -> np.ndarray:
        """
        Return (n_calls, 11) feature matrix.

        Features are ordered as in FEATURE_COLUMNS:
        [duration, low_freq, high_freq, principal_freq, bandwidth,
         freq_stdev, slope, sinuosity, snr, entropy, mean_power]
        """
        return np.column_stack([
            self.duration,
            self.low_freq,
            self.high_freq,
            self.principal_freq,
            self.bandwidth,
            self.freq_stdev,
            self.slope,
            self.sinuosity,
            self.snr,
            self.entropy,
            self.mean_power,
        ])

    @classmethod
    def from_dataframe(cls, df: pd.DataFrame, filename: str) -> 'EnrichedCallData':
        """Create EnrichedCallData from a pandas DataFrame."""
        return cls(
            duration=df['duration'].values,
            low_freq=df['low_freq'].values,
            high_freq=df['high_freq'].values,
            principal_freq=df['principal_freq'].values,
            bandwidth=df['bandwidth'].values,
            freq_stdev=df['freq_stdev'].values,
            slope=df['slope'].values,
            sinuosity=df['sinuosity'].values,
            snr=df['snr'].values,
            entropy=df['entropy'].values,
            mean_power=df['mean_power'].values,
            filename=filename,
            n_calls=len(df),
        )


def load_enriched_csv(filepath: str) -> EnrichedCallData:
    """
    Load enriched features from a CSV file.

    Args:
        filepath: Path to the CSV file generated by ExportEnrichedFeatures.m

    Returns:
        EnrichedCallData object containing the features.

    Raises:
        ValueError: If required columns are missing.
        FileNotFoundError: If the file doesn't exist.
    """
    filepath = Path(filepath)

    if not filepath.exists():
        raise FileNotFoundError(f"CSV file not found: {filepath}")

    df = pd.read_csv(filepath)

    # Validate columns
    missing_cols = set(FEATURE_COLUMNS) - set(df.columns)
    if missing_cols:
        raise ValueError(f"Missing required columns: {missing_cols}")

    # Handle NaN/Inf values
    for col in FEATURE_COLUMNS:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())

    return EnrichedCallData.from_dataframe(df, filepath.name)


def load_all_enriched_csv(
    directory: str,
    recursive: bool = False
) -> list[EnrichedCallData]:
    """
    Load all enriched feature CSV files from a directory.

    Args:
        directory: Path to directory containing CSV files.
        recursive: Whether to search subdirectories.

    Returns:
        List of EnrichedCallData objects.
    """
    directory = Path(directory)

    if recursive:
        csv_files = list(directory.rglob("*_features.csv"))
    else:
        csv_files = list(directory.glob("*_features.csv"))

    if not csv_files:
        # Try loading any CSV files if pattern doesn't match
        if recursive:
            csv_files = list(directory.rglob("*.csv"))
        else:
            csv_files = list(directory.glob("*.csv"))

    results = []
    for csv_file in sorted(csv_files):
        try:
            call_data = load_enriched_csv(csv_file)
            results.append(call_data)
        except Exception as e:
            print(f"Warning: Failed to load {csv_file}: {e}")

    return results


def get_recording_name(csv_filename: str) -> str:
    """
    Extract the original recording name from CSV filename.

    Removes '_features.csv' suffix if present.

    Args:
        csv_filename: Name of the CSV file.

    Returns:
        Recording name without the features suffix.
    """
    name = Path(csv_filename).stem
    if name.endswith('_features'):
        name = name[:-9]  # Remove '_features'
    return name


def get_enriched_feature_stats(call_data_list: list[EnrichedCallData]) -> dict:
    """
    Compute statistics across all calls in the dataset.

    Args:
        call_data_list: List of EnrichedCallData objects.

    Returns:
        Dictionary with per-feature statistics.
    """
    all_features = np.concatenate(
        [cd.get_feature_matrix() for cd in call_data_list],
        axis=0
    )

    stats = {
        'n_recordings': len(call_data_list),
        'total_calls': all_features.shape[0],
        'per_feature': {}
    }

    for i, col_name in enumerate(FEATURE_COLUMNS):
        col_data = all_features[:, i]
        stats['per_feature'][col_name] = {
            'min': float(np.min(col_data)),
            'max': float(np.max(col_data)),
            'mean': float(np.mean(col_data)),
            'std': float(np.std(col_data)),
            'median': float(np.median(col_data)),
        }

    return stats


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        test_dir = sys.argv[1]
    else:
        test_dir = "../enriched_features"

    print(f"Loading enriched CSV files from: {test_dir}")
    data = load_all_enriched_csv(test_dir)

    print(f"\nLoaded {len(data)} recordings")
    for cd in data:
        print(f"  {cd.filename}: {cd.n_calls} calls")

    if data:
        print("\nDataset statistics:")
        stats = get_enriched_feature_stats(data)
        print(f"  Total calls: {stats['total_calls']}")
        for feat, feat_stats in stats['per_feature'].items():
            print(f"  {feat}: mean={feat_stats['mean']:.3f}, std={feat_stats['std']:.3f}")
